package e2e

var login = step{name: "login", args: []string{"login", "--cookies", "$COOKIES"}}

// All scenarios work under /bnd-test in the netdisk.
var scenarios = []scenario{
	{
		name: "files",
		files: map[string][]byte{
			"up/hello.txt":     []byte("hello, bnd\n"),
			"up/empty.txt":     nil,
			"up/dir/x.txt":     []byte("x\n"),
			"up/dir/sub/y.bin": random(70<<10, 1),
		},
		steps: []step{
			login,
			{name: "cleanup", args: []string{"rm", "/bnd-test"}},
			{name: "mkdir", args: []string{"mkdir", "/bnd-test/a/b"}},
			{name: "mkdir-exists", args: []string{"mkdir", "/bnd-test/a"}},
			{name: "upload", args: []string{"upload", "$WORK/up", "/bnd-test"}, sorted: true},
			{name: "upload-again", args: []string{"upload", "--json", "$WORK/up", "/bnd-test"}},
			{name: "ls", args: []string{"ls", "/bnd-test/up"}},
			{name: "ls-long-size", args: []string{"ls", "-l", "--sort", "size", "--desc", "/bnd-test/up"}},
			{name: "ls-json", args: []string{"ls", "--json", "/bnd-test/up/dir"}},
			{name: "ls-glob", args: []string{"ls", "/bnd-test/up/*.txt"}},
			{name: "ls-glob-none", args: []string{"ls", "/bnd-test/up/*.zip"}},
			{name: "ls-missing", args: []string{"ls", "/bnd-test/nope"}},
			{name: "ls-missing-json", args: []string{"--json", "ls", "/bnd-test/nope"}},
			{name: "tree", args: []string{"tree", "/bnd-test"}},
			{name: "tree-depth", args: []string{"tree", "--depth", "1", "--json", "/bnd-test"}},
			{name: "meta", args: []string{"meta", "/bnd-test/up/hello.txt", "/bnd-test/up/dir"}},
			{name: "cd", args: []string{"cd", "/bnd-test/up"}},
			{name: "pwd", args: []string{"pwd", "--json"}},
			{name: "cp-rename", args: []string{"cp", "hello.txt", "copy.txt"}},
			{name: "cp-into-dir", args: []string{"cp", "copy.txt", "dir"}},
			{name: "cp-onto-file", args: []string{"cp", "hello.txt", "copy.txt"}},
			{name: "mv-rename", args: []string{"mv", "copy.txt", "renamed.txt"}},
			{name: "mv-glob", args: []string{"mv", "dir/*.txt", "/bnd-test/a"}},
			{name: "cp-missing", args: []string{"cp", "nope", "x"}},
			{name: "savedir", args: []string{"config", "set", "--save-dir", "$WORK/dl"}},
			{name: "download", args: []string{"download", "/bnd-test/up"}, sorted: true,
				check: same("up/hello.txt", "dl/up/hello.txt", "up/empty.txt", "dl/up/empty.txt", "up/dir/sub/y.bin", "dl/up/dir/sub/y.bin")},
			{name: "download-again", args: []string{"download", "--json", "/bnd-test/up"}},
			{name: "download-file", args: []string{"download", "/bnd-test/up/hello.txt"}},
			{name: "download-overwrite", args: []string{"download", "--overwrite", "-o", "$WORK/dl", "/bnd-test/up/hello.txt"}},
			{name: "download-missing", args: []string{"download", "/bnd-test/nope"}},
			{name: "share", args: []string{"share", "create", "-p", "e2et", "--days", "1", "hello.txt"},
				capture: map[string]string{"SHAREID": `shareId: (\d+)`, "LINK": `链接: (\S+)`}},
			{name: "share-save-own", args: []string{"share", "save", "$LINK", "e2et"}},
			{name: "share-save-bad-pwd", args: []string{"share", "save", "--json", "$LINK", "zzzz"}},
			{name: "share-cancel", args: []string{"share", "cancel", "$SHAREID"}},
			{name: "rm-glob", args: []string{"rm", "/bnd-test/a/*"}},
			{name: "rm-missing", args: []string{"rm", "--json", "/bnd-test/nope"}},
			{name: "rm", args: []string{"rm", "/bnd-test"}},
		},
	},
	{
		name:  "large",
		files: map[string][]byte{"big.bin": random(9<<20+321, 2)}, // three upload blocks
		steps: []step{
			login,
			{name: "cleanup", args: []string{"rm", "/bnd-test"}},
			{name: "upload", args: []string{"upload", "--json", "$WORK/big.bin", "/bnd-test"}},
			{name: "meta", args: []string{"meta", "/bnd-test/big.bin"}},
			{name: "download", args: []string{"download", "-p", "4", "-o", "$WORK/dl", "/bnd-test/big.bin"},
				check: same("big.bin", "dl/big.bin")},
			{name: "rm", args: []string{"rm", "/bnd-test"}},
		},
	},
	{
		name: "agent",
		steps: []step{
			{name: "no-command", args: []string{}},
			{name: "version-json", args: []string{"--json", "--version"}},
			{name: "who-logged-out", args: []string{"who", "--json"}},
			{name: "quota-logged-out", args: []string{"quota", "--json"}},
			{name: "unknown-flag", args: []string{"ls", "--json", "--nope"}},
			{name: "missing-arg", args: []string{"mkdir"}},
			{name: "parent-only", args: []string{"share", "--json"}},
			login,
			{name: "users", args: []string{"users", "--json"}},
			{name: "config", args: []string{"config", "--json"}},
			{name: "config-set", args: []string{"config", "set", "--connections", "4", "--download-limit", "2MB"}},
			{name: "config-bad", args: []string{"config", "set", "--connections", "0"}},
			{name: "logout-no-tty", args: []string{"logout"}},
			{name: "logout", args: []string{"logout", "-y", "--json"}},
			{name: "who-after-logout", args: []string{"who"}},
		},
	},
}
