package e2e

var login = step{name: "login", args: []string{"login", "--cookies", "$COOKIES"}}

// Every scenario works in its own directory $ROOT under /bdc-test.
var scenarios = []scenario{
	{
		name: "files",
		files: map[string][]byte{
			"up/hello.txt":     []byte("hello, bdc\n"),
			"up/empty.txt":     nil,
			"up/[1].txt":       []byte("bracket\n"),
			"up/1.txt":         []byte("one\n"),
			"up/dir/x.txt":     []byte("x\n"),
			"up/dir/sub/y.bin": random(70<<10, 1),
			"up/other/x.txt":   []byte("other x\n"),
		},
		steps: []step{
			login,
			{name: "mkdir", args: []string{"mkdir", "$ROOT/a/b"}},
			{name: "mkdir-again", args: []string{"mkdir", "--json", "$ROOT/a"}},
			{name: "upload", args: []string{"upload", "$WORK/up", "$ROOT"}, sorted: true},
			{name: "upload-again", args: []string{"upload", "--json", "$WORK/up", "$ROOT"}},
			{name: "ls", args: []string{"ls", "$ROOT/up"}},
			{name: "ls-long-size", args: []string{"ls", "-l", "--sort", "size", "--desc", "$ROOT/up"}},
			{name: "ls-json", args: []string{"ls", "--json", "$ROOT/up/dir"}},
			{name: "ls-glob", args: []string{"ls", "$ROOT/up/*.txt"}},
			{name: "ls-literal-brackets", args: []string{"ls", "$ROOT/up/[1].txt"}},
			{name: "ls-glob-dirs", args: []string{"ls", "--json", "$ROOT/up/*/x.txt"}},
			{name: "ls-glob-none", args: []string{"ls", "$ROOT/up/*.zip"}},
			{name: "ls-partial", args: []string{"ls", "--json", "$ROOT/up/dir", "$ROOT/nope"}},
			{name: "tree", args: []string{"tree", "$ROOT"}},
			{name: "tree-depth", args: []string{"tree", "--depth", "1", "--json", "$ROOT"}},
			{name: "meta", args: []string{"meta", "$ROOT/up/hello.txt", "$ROOT/up/dir"}},
			{name: "cd", args: []string{"cd", "$ROOT/up"}},
			{name: "pwd", args: []string{"pwd", "--json"}},
			{name: "cp-rename", args: []string{"cp", "hello.txt", "copy.txt"}},
			{name: "cp-into-dir", args: []string{"cp", "copy.txt", "dir"}},
			{name: "cp-onto-file", args: []string{"cp", "hello.txt", "copy.txt"}},
			{name: "cp-many-new-dir", args: []string{"cp", "hello.txt", "1.txt", "newdir"}},
			{name: "cp-same-names", args: []string{"cp", "dir/x.txt", "other/x.txt", "newdir"}},
			{name: "mv-rename", args: []string{"mv", "copy.txt", "renamed.txt"}},
			{name: "mv-glob", args: []string{"mv", "dir/*.txt", "$ROOT/a"}},
			{name: "cp-missing", args: []string{"cp", "nope", "x"}},
			{name: "savedir", args: []string{"config", "set", "--save-dir", "$WORK/dl"}},
			{name: "download", args: []string{"download", "$ROOT/up"}, sorted: true,
				check: same("up/hello.txt", "dl/up/hello.txt", "up/empty.txt", "dl/up/empty.txt", "up/dir/sub/y.bin", "dl/up/dir/sub/y.bin", "up/[1].txt", "dl/up/[1].txt")},
			{name: "download-again", args: []string{"download", "--json", "$ROOT/up"}},
			{name: "download-same-target", args: []string{"download", "--json", "-o", "$WORK/dl3", "$ROOT/up/other/x.txt", "$ROOT/a/x.txt"}},
			{name: "download-overwrite", args: []string{"download", "--overwrite", "$ROOT/up/hello.txt"}},
			{name: "download-partial", args: []string{"download", "--json", "-o", "$WORK/dl4", "$ROOT/up/hello.txt", "$ROOT/nope"}},
			{name: "share", args: []string{"share", "create", "-p", "e2et", "--days", "1", "hello.txt"},
				capture: map[string]string{"SHAREID": `shareId: (\d+)`, "LINK": `链接: (\S+)`}},
			{name: "share-save-own", args: []string{"share", "save", "$LINK", "e2et"}},
			{name: "share-save-bad-pwd", args: []string{"share", "save", "--json", "$LINK", "zzzz"}},
			{name: "share-cancel", args: []string{"share", "cancel", "$SHAREID"}},
			{name: "rm-literal-brackets", args: []string{"rm", "$ROOT/up/[1].txt"}},
			{name: "rm-glob", args: []string{"rm", "$ROOT/a/*"}},
			{name: "rm-missing", args: []string{"rm", "--json", "$ROOT/nope"}},
			{name: "rm", args: []string{"rm", "$ROOT"}},
		},
	},
	{
		name:  "large",
		files: map[string][]byte{"big.bin": random(9<<20+321, 2)}, // three upload blocks
		steps: []step{
			login,
			{name: "upload", args: []string{"upload", "--json", "$WORK/big.bin", "$ROOT"}},
			{name: "meta", args: []string{"meta", "--json", "$ROOT/big.bin"}}, // no md5: stored in blocks
			{name: "download", args: []string{"download", "-p", "4", "-o", "$WORK/dl", "$ROOT/big.bin"},
				check: same("big.bin", "dl/big.bin")},
			{name: "rm", args: []string{"rm", "$ROOT"}},
		},
	},
	{
		name: "agent",
		steps: []step{
			{name: "no-command", args: []string{}},
			{name: "version-json", args: []string{"--json", "--version"}},
			{name: "who-logged-out", args: []string{"who", "--json=true"}},
			{name: "quota-logged-out", args: []string{"quota", "--json"}},
			{name: "unknown-flag", args: []string{"ls", "--json", "--nope"}},
			{name: "missing-arg", args: []string{"mkdir"}},
			{name: "parent-only", args: []string{"share", "--json"}},
			login,
			{name: "users", args: []string{"users", "--json"}},
			{name: "config", args: []string{"config", "--json"}},
			{name: "config-set", args: []string{"config", "set", "--connections", "4", "--download-limit", "2MB"}},
			{name: "config-bad", args: []string{"config", "set", "--connections", "0"}},
			{name: "logout-no-tty", args: []string{"logout"}},
			{name: "logout", args: []string{"logout", "-y", "--json"}},
			{name: "who-after-logout", args: []string{"who"}},
			{name: "bad-login", args: []string{"login", "--json", "--cookies", "BDUSS=invalid"}},
		},
	},
}
